from django.db import models
from django.urls import reverse
from contacts.models import Person


class Doctor(Person):

    ACA = 'ACUPUNCTURE(ACA)'
    MAI = 'ALLERGY AND IMMUNOLOGY(MAI)'
    MAA = 'ANESTHESIOLOGY(MAA)'
    DCH = 'CHIROPRACTIC(DCH)'
    DEN = 'DENTISTRY(DEN)'
    MDE = 'DERMATOLOGY(MDE)'
    MEM = 'EMERGENCY MEDICINE(MEM)'
    MFP = 'FAMILY PRACTICE(MFP)'
    MPM = 'GENERAL PREVENTATIVE MEDICINE(MPM)'
    MHH = 'HAND(MHH)'
    MMM = 'INTERNAL MEDICINE(MMM)'
    MMV = 'INTERNAL MEDICINE-CARDIOVASCULAR DISEASE(MMV)'
    MME = 'INTERNAL MEDICINE-ENDOCRINOLOGY DIABETES AND METBOLISM(MME)'
    MMG = 'INTERNAL MEDICINE-GASTROENTEROLOGY(MMG)'
    MMH = 'INTERNAL MEDICINE-HEMATOLOY(MMH)'
    MMI = 'INTERNAL MEDICINE-INFECTIOUS DISEASE(MMI)'
    MMN = 'INTERNAL MEDICINE-NEPHROLOGY(MMN)'
    MMP = 'INTERNAL MEDICINE-PULMONARY DISEASE(MMP)'
    MMR = 'INTERNAL MEDICINE-RHEUMATOLOGY(MMR)'
    MOQ = 'MEDICINE OTHERWISE QUALIFIED(MOQ)'
    MNS = 'NEUROLOGICAL SURGERY - OTHER THAN SPINE(MNS)'
    MPN = 'NEUROLOGY(MPN)'
    MOG = 'OBSTETRICS AND GYNECOLOGY(MOG)'
    MPO = 'OCCUPATIONAL MEDICINE(MPO)'
    MMO = 'ONCOLOGY-INTERNAL MEDICINE(MMO)'
    MOP = 'OPHTHALMOLOGY(MOP)'
    OPT = 'OPTOMETRY(OPT)'
    MOS = 'ORTHOPAEDIC SURGERY - OTHER THAN SPINE OR HAND(MOS)'
    MTO = 'OTOLARYNGOLOGY(MTO)'
    MPA = 'PAIN MEDICINE(MPA)'
    MHA = 'PATHOLOGY(MHA)'
    MPR = 'PHYSICAL MEDICINE AND REHABILITATION(MPR)'
    MPS = 'PLASTIC SURGERY - OTHER THAN HAND(MPS)'
    POD = 'PODIATRY(POD)'
    MPD = 'PSYCHIATRY(MPD)'
    PSY = 'PSYCHOLOGY(PSY)'
    MNB = 'SPINE(MNB)'
    MSY = 'SURGERY - OTHER THAN SPINE OR HAND(MSY)'
    MSG = 'SURGERY - GENERAL VASCULAR(MSG)'
    MTS = 'THORACIC SURGERY(MTS)'
    MTT = 'TOXICOLOGY(MTT)'
    MUU = 'UROLOGY(MUU)'
    OTHER = 'OTHER'

    SPECIALTY = [
        (ACA, 'ACUPUNCTURE'),
        (MAI, 'ALLERGY AND IMMUNOLOGY'),
        (MAA, 'ANESTHESIOLOGY'),
        (DCH, 'CHIROPRACTIC'),
        (DEN, 'DENTISTRY'),
        (MDE, 'DERMATOLOGY'),
        (MEM, 'EMERGENCY MEDICINE'),
        (MFP, 'FAMILY PRACTICE'),
        (MPM, 'GENERAL PREVENTATIVE MEDICINE'),
        (MHH, 'HAND'),
        (MMM, 'INTERNAL MEDICINE'),
        (MMV, 'INTERNAL MEDICINE-CARDIOVASCULAR DISEASE'),
        (MME, 'INTERNAL MEDICINE-ENDOCRINOLOGY DIABETES AND METBOLISM'),
        (MMG, 'INTERNAL MEDICINE-GASTROENTEROLOGY'),
        (MMH, 'INTERNAL MEDICINE-HEMATOLOY'),
        (MMI, 'INTERNAL MEDICINE-INFECTIOUS DISEASE'),
        (MMN, 'INTERNAL MEDICINE-NEPHROLOGY'),
        (MMP, 'INTERNAL MEDICINE-PULMONARY DISEASE'),
        (MMR, 'INTERNAL MEDICINE-RHEUMATOLOGY'),
        (MOQ, 'MEDICINE OTHERWISE QUALIFIED'),
        (MNS, 'NEUROLOGICAL SURGERY (OTHER THAN SPINE)'),
        (MPN, 'NEUROLOGY'),
        (MOG, 'OBSTETRICS AND GYNECOLOGY'),
        (MPO, 'OCCUPATIONAL MEDICINE'),
        (MMO, 'ONCOLOGY-INTERNAL MEDICINE'),
        (MOP, 'OPHTHALMOLOGY'),
        (OPT, 'OPTOMETRY'),
        (MOS, 'ORTHOPAEDIC SURGERY (OTHER THAN SPINE OR HAND'),
        (MTO, 'OTOLARYNGOLOGY'),
        (MPA, 'PAIN MEDICINE'),
        (MHA, 'PATHOLOGY'),
        (MPR, 'PHYSICAL MEDICINE AND REHABILITATION'),
        (MPS, 'PLASTIC SURGERY (OTHER THAN HAND'),
        (POD, 'PODIATRY'),
        (MPD, 'PSYCHIATRY'),
        (PSY, 'PSYCHOLOGY'),
        (MNB, 'SPINE'),
        (MSY, 'SURGERY (OTHER THAN SPINE OR HAND'),
        (MSG, 'SURGERY-GENERAL VASCULAR'),
        (MTS, 'THORACIC SURGERY'),
        (MTT, 'TOXICOLOGY'),
        (MUU, 'UROLOGY'),
        (OTHER, 'OTHER')
    ]
    specialty = models.CharField(max_length=200, choices=SPECIALTY)

    # Doctor preferences
    by_hardcopy = models.BooleanField(default=False)
    by_cd = models.BooleanField(default=False)
    by_usb = models.BooleanField(default=False)
    by_email = models.BooleanField(default=False)

    # For UpdateView to reverse back to after form POST request
    def get_absolute_url(self):
        return reverse('doctor_detail', kwargs={'pk': self.pk})